### ISSUE TITLE
IllegalStateException: Cannot access request header fields after connection is set

### ISSUE THREAD

**Issue by apognu** [kittinunf/Fuel#229] opened 2017-08-26 10:20 UTC
Hello,

I have a rather simple Android application that makes a GET request when it starts, and then possibly repeats it if the user pulls to refresh. Each request must have a JWT in the Authorization header that is generated just as the requested is made.

The first request succeeds properly, but as soon as I pull to refresh, the request returns a ```Result.Failure``` with the message ```IllegalStateException: Cannot access request header fields after connection is set```.

A pass on the debugger and the remote server tells me that:
 * the request has a ```200``` response code
 * [this line](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L51
) throws the exception.

This is the method (with inputs simplified)  that launches the requests, in the case I'm doing something wrong:

```
fun getSecrets(context: Context, cb: (Boolean, List<String>) -> Unit) {
    val url = "<properurl>"
    val token = "<properjwt>"

    try {
      Fuel.get(url)
        .header(mapOf("Authorization" to token))
        .responseObject(APIResponse.Deserializer()) { _, _, result ->
          when (result) {
            is Result.Failure -> cb(false, listOf())
            is Result.Success -> {
              val (apiResponse, error) = result

              when (error) {
                null -> cb(true, apiResponse?.secrets ?: listOf())
                else -> cb(false, listOf())
              }
            }
          }
        }
    } catch (e: Exception) {
      cb(false, listOf())
    }
  }
```

Thanks.

**Comment by apognu** [comment] 2017-08-26 13:21
Some more information: any subsequent request fails in the same fashion, even on different URLs (different path and/or different domain altogether).

**Comment by mradzinski** [comment] 2017-08-26 18:49
Same exception I'm having on #228 but @kittinunf says he can't reproduce it.

**Comment by apognu** [comment] 2017-08-27 10:42
Well, seems I fixed the issue on my end, I was using the Kotlin plugin version 1.1.2-4 when I encountered the error. Updated to 1.1.4 and now all my requests seem to go through.

Here's my config in case this could help you:

There you go:
 * Kotlin 1.1.4
 * Gradle 4.1
 * compileSdkVersion 26

If you need any other info for #228, don't hesitate to ask.

**Comment by kittinunf** [comment] 2017-08-28 12:03
So just updating to version 1.1.4 and the issue resolves. That sounds a bit magical.

**Comment by mradzinski** [comment] 2017-08-28 12:20
Not really. I actually updated to 1.1.4-2 and it broke. I don't believe it has anything to do with Kotlin itself but with the compile version, Android gradle plugins and things like that.

**Comment by kittinunf** [comment] 2017-08-28 12:34
@mradzinski hey, thank you. If you could, would you help me get to bottom of this. 

First of all, let's us talk in #228, shall we? 

I will close this issue first as @apognu reported that it fixed from his end.

**Closed** 2017-08-28 12:36 UTC
