### ISSUE TITLE
GET become POST

### ISSUE THREAD

**Issue by dpmaycry** [kittinunf/Fuel#406] opened 2018-08-03 10:19 UTC
I new a `fuelManager = FuelManger()`, then use it to luanch a GET request:
```kotlin
fuelManager.request(Method.GET,Constants.update_suffix,params).responseObject(UpdateData.Deserializer()) { request, response, result ->
            callback(result)
        }
```
but turns out to be a POST request.
Mightbe a bug

**Comment by kittinunf** [comment] 2018-08-03 16:32
What does it mean that it becomes post? Fuel has a test to call endpoint that accepts GET and it works correctly? Could you please elaborate more on this?

**Comment by dpmaycry** [comment] 2018-08-05 09:39
Fuel works fine in singleton mode
When I decide to use mutiple fuel in my android app,I create FuelManger(),but the same api that worked fine with FuelManager.instance keep report http error 405.
So I used Charles to see whats going on, and the request that set with Method.GET  under FuelManger() became POST in real request witch confused me a lot.
Thank u for reply

**Comment by SleeplessByte** [comment] 2018-09-13 16:13
@dpmaycry do you have a minimal reproducable sample or code snippet we can run to further investigate this issue?

**Comment by SleeplessByte** [comment] 2018-10-18 15:53
Closing this because not reproducible. Feel free to comment here with a sample and we'll re-open.

**Closed by SleeplessByte** 2018-10-18 15:53 UTC

**Comment by easazade** [comment] 2019-11-14 10:36
4 month ago i switched back to using okhttp because my post requests was being sent as get requests. i tried to find out when exactly it happens and create a small project to reproduce the bug but it wasn't happening in the small project. after that since i had a wrapper for my network client in my work project i just changed the implementation a little  and moved on
