### ISSUE TITLE
httpCode and httpMessage fields in HttpException

### ISSUE THREAD

**Issue by anatolykislov** [kittinunf/Fuel#206] opened 2017-07-26 14:40 UTC
HttpException's constructor parameters httpCode and httpMessage can actually be class fields. This fields is useful because can be used to determine behavior on exception caught from blocking request.

**Comment by anatolykislov** [comment] 2017-07-26 15:42
Resolved. Actually, FuelError exception is used. Status code can be obtained from response field.

**Comment by kittinunf** [comment] 2017-08-06 04:51
Closing this then.

**Closed by kittinunf** 2017-08-06 04:51 UTC

**Comment by mobiletoly** [comment] 2018-05-27 20:13
I am using fuel-coroutines and I am stuck with this code:
```
override suspend fun queryUserByToken(bearerToken: String) : AccountUser {
        try {
            return "$endpointURL/user/me".httpGet().header(mapOf("Authorization" to "Bearer $bearerToken"))
                    .awaitObject(Account.Deserializer()).third.component1()!!
        } catch(ex: com.github.kittinunf.fuel.core.HttpException) {
            // I want to know httpStatusCode here, so I could rethrow more specific exception
        }
    }
```

any specific reason why not to expose httpStatusCode in HttpException?

**Comment by dany-kun** [comment] 2018-06-06 20:55
I think the problem is more from coroutines not throwing a FuelError:   https://github.com/kittinunf/Fuel/issues/358
A FuelError would give you the info you need.
