### ISSUE TITLE
Enable/Disable URL Encoding for Path Params

### ISSUE THREAD

**Issue by gokhan** [kittinunf/fuel#759] opened 2020-06-29 07:59 UTC
# Feature Request

## Description
I would like to have URL encoding: true/false option therefore some of the endpoint requests may not fail. For example, on Google Hangouts Chat, if you create a Webhook URL for your room, it gives you an endpoint like this:

https://chat.googleapis.com/v1/spaces/AAAA_raXXXX/messages?key=AIzbSyDdI0XXXXXXX-WEfRq3CPzqKqqsHI&token=SIxI-OawDJ0NSwXXXXXXX**%3D**

After the encoding, since the Google Chat Room Webhook token values includes **'%'** the token becomes invalid after encoding then request is failing.

I have checked the documentation about it but could not find anything related with it. I was happily using Fuel on my project but I could not use it for my chat notification.

Thanks a lot!

**Comment by SleeplessByte** [comment] 2020-06-29 13:14
Hi there. The correct way to handle this is to _decode_ the url before you _encode_ it again.

If you _really_ want to have this in Fuel, that's possible. Fuel is encoding the parameters using an Interceptor ([ParameterEncoder](https://github.com/kittinunf/fuel/blob/7b56b22799905ea3c4b7b26addd84dc978983247/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoder.kt)). You can **remove** this one and add a custom one.

**Comment by SleeplessByte** [comment] 2020-07-13 17:27
I'm going to close this issue as the above is implemented and works as intended. If you want to propose a different API, feel free to open a anew issue with the proposal :)

**Closed by SleeplessByte** 2020-07-13 17:27 UTC
