### ISSUE TITLE
Why httpGet() causes a com.github.kittinunf.fuel.core.BubbleFuelError: null?

### ISSUE THREAD

**Issue by MrSilverstein** [kittinunf/fuel#606] opened 2019-03-06 13:30 UTC
## Description
I have a rest call realized by fuel library in my Android app Kotlin project. While attempting to call httpGet I get this

`
Caused by: com.github.kittinunf.fuel.core.BubbleFuelError: null com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84) 03-06 11:32:39.112 6328-6328/com.example.demo I/System.out: com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:24) com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44) com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14) com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166) com.github.kittinunf.fuel.core.requests.DefaultRequest.responseObject(DefaultRequest.kt:463)
`

## Question
Most probably the response seem null, and it fails during deserialization?
What can I do there?

**Comment by SleeplessByte** [comment] 2019-03-07 11:59
You're calling `.responseObject`. I think calling `.responseBytes` or similar should work.

**Comment by sokarcreative** [comment] 2019-03-17 19:01
Same here

**Comment by KiteCapital** [comment] 2019-04-02 08:22
I also get the same error when using :

`var jsonArray = Fuel.get("http://name.pythonanywhere.com/api/v1/prog").header(Headers.COOKIE, cookie).responseJson().third.get().array()`

but it's funny that the code works when I use: 
`Fuel.get("http://name.pythonanywhere.com/api/v1/prog").header(Headers.COOKIE, cookie).responseJson { request: Request, response: Response, result: Result<FuelJson, FuelError> ->
            //incident_count = (count_occurrences('{', response.body().toString()) - 1).toString()
            for (i in 0..result.get().array().length() -1){
                myReportLat = result.get().array().getJSONObject(i)["latitude"].toString()
                myReportLong= result.get().array().getJSONObject(i)["longitude"].toString()
            }`

Of which now with the later segment I won't be able to access the values of longitude and latitude outside the Fuel block

**Comment by BVADY** [comment] 2019-04-03 07:48
I can't figure out why this is not working for me:
 
`val (_,_,result )= Fuel.get(requestUrl).responseString()`

And this works fine:
```
requestUrl.httpGet().responseString { _, _, result ->
     when (result) {
          is Result.Success -> {
             // do something on success
          }
          is Result.Failure -> {
             // do something on fail
          }
     }
}
```

I would like to work as in the first example, because I would like to return this result.

**Comment by baillyjamy** [comment] 2019-04-29 20:43
I have the same errors as those mentioned above with the responseObject method. Blocking queries seem unusable.

**Comment by kittinunf** [comment] 2019-05-02 12:55
Assuming that you guys are running on Android, it sounds to me that, you all might be running into `NetworkOnMainThreadException`?

Can you try to see `result.error.exception` is `NetworkOnMainThreadException`? @baillyjamy @BVADY @KiteCapital ?

**Comment by kittinunf** [comment] 2019-05-02 13:03
@sokarcreative For your case, since you are using the coroutine extension. `NetworkOnMainThreadException` doesn't apply to you. Can you help me point to the runnable snippet so I can try on my end?


PS. 

I am running this on Android project and it works perfectly.

```
private suspend fun execute() {
  val githubIssue = "https://api.github.com/repos/kittinunf/Fuel/issues/1".httpGet().awaitObject(Issue.Deserializer())
  println(issue)
}
```
Output

```
I/System.out: Issue(id=84908363, title=create readme file, url=https://api.github.com/repos/kittinunf/fuel/issues/1)
```

**Comment by iNoles** [comment] 2019-05-03 02:30
I would like to know these information to reproduce 
1) Android Version
2) Fuel Version
3) URL address

**Comment by kittinunf** [comment] 2019-05-13 11:21
I would like to hear back on this? We also released new version https://github.com/kittinunf/fuel/releases/tag/2.1.0, do you think it should help solve or at the very least investigate what's going on?

**Comment by baillyjamy** [comment] 2019-05-24 21:00
Hello,
Effectively, it was an error of inattention, my synchronous request was in the android main thread. A beginner's mistake. I should have answered faster and told you. I'm sorry. 
Anyway, thank you for the modification, I just reproduced this problem and the error is clearer. I think you can close this issue. Sorry again.

**Closed** 2019-05-25 11:43 UTC
Labels: :bug: bug, :thinking: question
