### ISSUE TITLE
using httpGet() progress callback never fired

### ISSUE THREAD

**Issue by holyman2k** [kittinunf/Fuel#189] opened 2017-07-03 02:12 UTC
using kotlin "http://someurl".httpGet().progress({}).responseJson()

The progress block is never fired

**Comment by babedev** [comment] 2017-08-02 08:14
`progress` is only use with download or upload right now.

```Kotlin
fun progress(handler: (readBytes: Long, totalBytes: Long) -> Unit): Request {
  if (taskRequest as? DownloadTaskRequest != null) {
    val download = taskRequest as DownloadTaskRequest
    download.apply {
      progressCallback = handler
    }
  } else if (taskRequest as? UploadTaskRequest != null) {
    val upload = taskRequest as UploadTaskRequest
    upload.apply {
      progressCallback = handler
    }
  } else {
    throw IllegalStateException("progress is only used with RequestType.DOWNLOAD or RequestType.UPLOAD")
  }

  return this
}
```

It would be great if we implement for another methods in the future 😄

**Comment by yoavst** [comment] 2017-08-22 17:08
Closing as duplicate of #146

**Closed by yoavst** 2017-08-22 17:08 UTC
