### ISSUE TITLE
DELETE not sending body even though it was specified

### ISSUE THREAD

**Issue by mishaxz** [kittinunf/Fuel#245] opened 2017-09-17 13:06 UTC
is this by design? or do I need to configure something? It shows the body in `request.toString()` but it does not send it with the actual request

**Comment by daleksandrovms** [comment] 2017-10-19 11:56
yes, i see the same...

**Comment by mishaxz** [comment] 2017-10-19 12:01
unfortunately because of this I had to switch to another library :( I really did like this library but I couldn't work around it

IF this behaviour ever changes, please drop a comment here so that I know about it - thanks!

**Comment by markGilchrist** [comment] 2018-09-12 17:11
I am closing this as I believe it is a duplicate of 306 and that is now merged in

**Closed by markGilchrist** 2018-09-12 17:11 UTC
