### ISSUE TITLE
A program crushes after uploading timeout.

### ISSUE THREAD

**Issue by CoolMind** [kittinunf/Fuel#552] opened 2018-11-28 16:21 UTC
## Description
A program crushes after uploading timeout.

## To Reproduce

1. Open a needed screen and turn off a connection.
2. Open a picture and upload it.
3. The application crashes with an error. In one device it is:
```
11-28 19:10:15.896 7759-7778/com.example.example.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.example.example.debug, PID: 7759
```
In an other it is:
```
2018-11-28 18:59:41.144 30250-30271/com.example.example.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.example.example.debug, PID: 30250
    java.net.SocketTimeoutException: timeout
        at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:39)
        at com.github.kittinunf.fuel.core.requests.SuspendingRequest.awaitResult(SuspendingRequest.kt:16)
        at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponse(Deserializable.kt:100)
        at CoroutinesKt$await$2.invokeSuspend(Coroutines.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:763)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:635)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:207)
        at java.net.URLConnection.getContentEncoding(URLConnection.java:520)
        at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:66)
        at com.github.kittinunf.fuel.toolbox.HttpClient.access$doRequest(HttpClient.kt:21)
        at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:36)
        at com.github.kittinunf.fuel.core.requests.SuspendingRequest.awaitResult(SuspendingRequest.kt:16) 
        at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponse(Deserializable.kt:100) 
        at CoroutinesKt$await$2.invokeSuspend(Coroutines.kt:19) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:203)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) 
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:763) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:635) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:207) 
        at java.net.URLConnection.getContentEncoding(URLConnection.java:520) 
        at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:66) 
        at com.github.kittinunf.fuel.toolbox.HttpClient.access$doRequest(HttpClient.kt:21) 
        at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:36) 
        at com.github.kittinunf.fuel.core.requests.SuspendingRequest.awaitResult(SuspendingRequest.kt:16) 
        at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponse(Deserializable.kt:100) 
        at CoroutinesKt$await$2.invokeSuspend(Coroutines.kt:19) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
```

### Development Machine
 - OS: [Windows 10]
 - IDE: [Android Studio]
 - Fuel version: [1.16.0]
 - Kotlin version: [1.3.10]

### Smartphone
 - OS: [Android 5.0.1, Android 8.1.0]

**Comment by SleeplessByte** [comment] 2018-11-28 16:43
Thank you for reporting! 

Duplicate of #358, fixed in `master`. You can use [jitpack](https://jitpack.io/#kittinunf/Fuel/fba92d4a21) to get the current commit -- or wait for it to drop. 

If you don't want to upgrade, temporarily wrap your code in try catch(error: Exception).

**Closed by SleeplessByte** 2018-11-28 16:43 UTC

**Comment by CoolMind** [comment] 2018-11-29 08:02
Thanks you, @SleeplessByte! I will wait some time.

**Comment by CoolMind** [comment] 2018-12-21 08:33
@SleeplessByte, as a release has not still been done, can you help me? I have:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```
    implementation 'com.github.kittinunf:Fuel:fba92d4a21' // Maybe a newer version, but I couldn't resolve.

Also want to have other libraries (fuel-android, fuel-gson, fuel-coroutines).

After building I get:

> Failed to resolve: com.github.kittinunf:Fuel:fba92d4a21
> Show in File
> Show in Project Structure dialog

**Comment by Turalllb** [comment] 2021-03-25 17:47
Is it possible that this bug is not closed correctly and these crashes, although they do not break the application, fly to firebase and spoil the statistics? In our case, all the same happens
